#!/bin/sh /etc/rc.common

# Copy this file to /etc/init.d/pydnsproxy and run service pydnsproxy enable

START=99
STOP=99
USE_PROCD=1

start_service() {
	logger "Starting pydnsproxy service..."
	procd_open_instance pydnsproxy
	procd_set_param command /usr/bin/python3 /usr/local/bin/pydnsproxy.py -c /etc/pydnsproxy.json
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance
}
